version: "3.7"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./conf:/etc/nginx/conf.d
    links:
      - php
  php:
    image: php:7-fpm
    build: .
    volumes:
      - ./code:/code
  db:
    image: mysql:8.0
    ports:
      - '6603:3306'
    environment:
      MYSQL_ROOT_PASSWORD: phppass